# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pustefix Framework 
email: mtld@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  The Pustefix Framework is an open-source Java web application framework for
  developing request-based MVC-style web applications using Spring, XML and XSLT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.pustefix-framework.org" # the base hostname & protocol for your site
github_username: pustefix-projects/pustefix-framework 

paginate: 5
paginate_path: "/blog/page:num/"

keywords: pustefix, framework, java, xml, xslt, spring, mvc
pustefix_version: 0.20.24

# Build settings
markdown: kramdown
